resources:
- name: booklit
  type: git
  source: {uri: "https://github.com/vito/booklit"}
  branch: main

jobs:
- name: unit
  plan:
  - get: booklit
    trigger: true
  - task: test
    file: booklit/ci/test.yml
