resources:
- name: code
  type: git
  source:
    uri: https://github.com/muzakkirsaifi123/spring-boot-example.git
    branch: Development
jobs:
  - name: compile
    plan:
      - get: code
        trigger: true
      - task: clean-compile
        config:
          platform: linux
          image_resource: 
            type: docker-image
            source: {repository: maven}
          inputs:
            - name: code
          run:
            path: mvn
            args:
              - clean
              - compile
              - -f
              - code/pom.xml     
  - name: test
    plan:
      - get: code
        trigger: true
      - task: clean-compile
        config:
          platform: linux
          image_resource: 
            type: docker-image
            source:
             repository: maven
             tag: 3.6.0-jdk-8-alpine
          inputs:
            - name: code
          run:
            path: mvn
            args:
              - clean
              - test
              - -f
              - code/pom.xml     
  - name: package
    plan:
      - get: code
        trigger: true
      - task: clean-compile
        config:
          platform: linux
          image_resource: 
            type: docker-image
            source: {repository: maven}
          inputs:
            - name: code
          run:
            path: mvn
            args:
              - clean
              - package
              - -f
              - code/pom.xml