---
resources:
  - name: code
    type: git
    source:
      uri: https://github.com/muzakkirsaifi123/Concourse-CI.git
      branch: master

jobs:
  - name: compile
    public: true
    serial: true
    plan: 
      - get: code
        trigger: true
      - task: clean-compile
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
          inputs:
            - name: code
          run: 
            path: mvn
            args:
              - clean
              - compile
              - -f
              - code/pom.xml 
    
  - name: package
    plan: 
      - get: code
        trigger: true
        passed: [compile]
      - task: mvn-package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
          inputs:
            - name: code
          run: 
            path: mvn
            args:
              - package
              - -f
              - code/pom.xml 
              
              
